import type { BattleApi, UnitView } from "../../kit/api";
import { defineCharacter } from "../../kit/character";

/**
 * Counter holding A4 overflow Energy. Gilgamesh's kit (1509) adds to it when
 * his Joint ATK Energy would exceed Saber's max, since the engine caps Energy.
 */
const OVERFLOW = "overflow-energy";
const RESONANCE = "core-resonance";
const CONSUMING = "core-resonance-consuming";
const ULTIMATES = "ultimates-used";
/** Core Resonance has no stated cap; statuses mirroring it must not clip it. */
const UNCAPPED = 999;

// Energy and Toughness come from AvatarSkillConfigLD (collab table), which the
// dossier does not read: Basic 20, Skill 30, Ultimate 5 (cost 360),
// Enhanced Basic 30 (+1 SP).
const BASIC_ENERGY = 20;
const SKILL_ENERGY = 30;
const ULTIMATE_ENERGY = 5;
const ENHANCED_BASIC_ENERGY = 30;

/** Saber — Destruction, Wind. */
export default defineCharacter("1014", (k) => {
  const resonanceEnergy = k.param("04", 5);
  const overflowCap = !k.a(2)
    ? 0
    : k.e(6)
      ? k.rankParam(6, 4)
      : k.traceParam(2, 1);

  const reactorCore = k.status({
    id: "dragon-reactor-core",
    origin: "talent",
    duration: { turns: k.param("04", 4) },
    modifiers: [{ stat: "dmgBoost", value: k.param("04", 3) }],
  });

  // Skill multiplier per Core Resonance consumed, applied for that Skill only.
  const resonanceBoost = k.status({
    id: "core-resonance-skill",
    origin: "skill",
    maxStacks: UNCAPPED,
    modifiers: [
      {
        stat: "multiplierBoost",
        value: k.param("02", 4) + (k.e(2) ? k.rankParam(2, 1) : 0),
        filter: { tags: ["skill"] },
      },
    ],
  });

  const goldenScepter = k.status({ id: "golden-scepter", origin: "ultimate" });
  const manaBurst = k.status({ id: "mana-burst", origin: "a2" });

  const crownSkill = k.status({
    id: "crown-of-the-star",
    origin: "a6",
    duration: { turns: k.traceParam(3, 2) },
    modifiers: [{ stat: "critDmg", value: k.traceParam(3, 1) }],
  });
  const crownResonance = k.status({
    id: "crown-of-the-star-resonance",
    origin: "a6",
    maxStacks: k.traceParam(3, 4),
    modifiers: [{ stat: "critDmg", value: k.traceParam(3, 3) }],
  });
  const roundTable = k.status({
    id: "round-table-oath",
    origin: "e2",
    maxStacks: k.rankParam(2, 3),
    modifiers: [{ stat: "defIgnore", value: k.rankParam(2, 2) }],
  });
  const sixteenWinters = k.status({
    id: "sixteen-winter-days",
    origin: "e4",
    maxStacks: k.rankParam(4, 3),
    modifiers: [
      {
        stat: "resPen",
        value: k.rankParam(4, 2),
        filter: { combatTypes: ["Wind"] },
      },
    ],
  });

  k.stat("a2", { stat: "critRate", value: k.traceParam(1, 1) });
  if (k.e(1)) {
    k.stat("e1", {
      stat: "dmgBoost",
      value: k.rankParam(1, 1),
      filter: { tags: ["ultimate"] },
    });
  }
  if (k.e(4)) {
    k.stat("e4", {
      stat: "resPen",
      value: k.rankParam(4, 1),
      filter: { combatTypes: ["Wind"] },
    });
  }
  if (k.e(6)) {
    k.stat("e6", {
      stat: "resPen",
      value: k.rankParam(6, 1),
      filter: { tags: ["ultimate"], combatTypes: ["Wind"] },
    });
  }

  /**
   * Regenerates Energy, keeping what exceeds max Energy as A4 overflow. The
   * ERR scale is estimated from the panel (momentary ERR buffs are ignored).
   */
  const regenerate = (ctx: BattleApi, amount: number, fixed: boolean) => {
    const self = ctx.self;
    const scale = fixed ? 1 : 1 + self.panelStat("energyRegen");
    const excess = Math.max(
      0,
      self.energy + amount * scale * ctx.weight - self.maxEnergy
    );
    ctx.gainEnergy(self, amount, { fixed });
    if (excess > 0 && overflowCap > 0 && ctx.weight > 0) {
      ctx.addCounter(self, OVERFLOW, excess / ctx.weight, overflowCap);
    }
  };

  const gainResonance = (ctx: BattleApi, amount: number) => {
    ctx.addCounter(ctx.self, RESONANCE, amount);
    if (k.a(3)) ctx.applyStatus(ctx.self, crownResonance, { stacks: amount });
    if (k.e(2)) ctx.applyStatus(ctx.self, roundTable, { stacks: amount });
  };

  /**
   * "Energy can be fully regenerated by [using the Skill and] consuming Core
   * Resonance": counts the Skill's own Energy, since consumption happens
   * after the Skill attack (A2 says so explicitly).
   */
  const skillFillsEnergy = (self: UnitView) => {
    const resonance = self.counter(RESONANCE);
    if (resonance <= 0) return false;
    const skillEnergy = SKILL_ENERGY * (1 + self.panelStat("energyRegen"));
    return (
      self.energy + skillEnergy + resonance * resonanceEnergy >=
      self.maxEnergy - 1e-9
    );
  };

  if (k.a(2)) {
    k.on("battleStart", "a4", { subject: "any" }, (ctx) => {
      const max = ctx.self.maxEnergy;
      if (ctx.self.energy < max * k.traceParam(2, 3)) {
        ctx.setEnergy(ctx.self, max * k.traceParam(2, 2));
      }
    });
  }
  k.on("battleStart", "talent", { subject: "any" }, (ctx) => {
    gainResonance(ctx, k.param("04", 8));
    if (k.a(1)) ctx.applyStatus(ctx.self, manaBurst);
  });

  // Saber's own Ultimate included ("any ally target").
  k.on(
    "actionStart",
    "talent",
    { subject: "ally", abilityKinds: ["ultimate"] },
    (ctx) => {
      ctx.applyStatus(ctx.self, reactorCore);
      gainResonance(ctx, k.param("04", 1));
    }
  );

  if (k.a(1)) {
    const releaseManaBurst = (ctx: BattleApi) => {
      if (!ctx.self.has(manaBurst) || !skillFillsEnergy(ctx.self)) return;
      ctx.removeStatus(ctx.self, manaBurst);
      ctx.gainSkillPoints(1);
      ctx.advanceAction(ctx.self, 1);
    };
    // Checked whenever Core Resonance or Energy can have changed: after ally
    // actions (Ultimates included) and after every turn (enemy hits).
    k.on("battleStart", "a2", { subject: "any" }, releaseManaBurst);
    k.on("actionEnd", "a2", { subject: "ally" }, releaseManaBurst);
    k.on("turnEnd", "a2", { subject: "any" }, releaseManaBurst);
  }

  // Ability Energy is regenerated in `after` (energy: 0) so that any excess
  // reaches the A4 overflow instead of being capped by the engine.
  k.ability({
    id: "basic",
    kind: "basic",
    energy: 0,
    hits: [
      { shape: "single", main: k.param("01", 1), toughness: { main: 10 } },
    ],
    after: (ctx) => {
      regenerate(ctx, BASIC_ENERGY, false);
      if (k.e(1)) gainResonance(ctx, k.rankParam(1, 2));
    },
  });

  k.ability({
    id: "skill",
    kind: "skill",
    energy: 0,
    hits: [
      {
        shape: "blast",
        main: k.param("02", 1),
        adjacent: k.param("02", 2),
        toughness: { main: 20, adjacent: 10 },
      },
    ],
    before: (ctx) => {
      if (k.a(3)) ctx.applyStatus(ctx.self, crownSkill);
      if (skillFillsEnergy(ctx.self)) {
        const resonance = ctx.self.counter(RESONANCE);
        ctx.setCounter(ctx.self, CONSUMING, 1);
        ctx.applyStatus(ctx.self, resonanceBoost, { setStacks: resonance });
      } else {
        ctx.setCounter(ctx.self, CONSUMING, 0);
        gainResonance(ctx, k.param("02", 3));
      }
    },
    after: (ctx) => {
      regenerate(ctx, SKILL_ENERGY, false);
      if (ctx.self.counter(CONSUMING) > 0) {
        const consumed = ctx.self.counter(RESONANCE);
        ctx.removeStatus(ctx.self, resonanceBoost);
        ctx.setCounter(ctx.self, RESONANCE, 0);
        ctx.setCounter(ctx.self, CONSUMING, 0);
        regenerate(ctx, consumed * resonanceEnergy, true);
      }
      if (k.e(1)) gainResonance(ctx, k.rankParam(1, 2));
    },
  });

  k.ability({
    id: "ultimate",
    kind: "ultimate",
    energy: 0,
    hits: [
      { shape: "aoe", each: k.param("03", 1), toughness: { each: 40 } },
      // Facts list 20 for the non-AoE role; as with other bounce skills it
      // is read as per instance (tracked: saber-ultimate-toughness).
      {
        shape: "bounce",
        each: k.param("03", 2),
        bounces: k.param("03", 3),
        toughness: { each: 20 },
      },
    ],
    after: (ctx) => {
      ctx.applyStatus(ctx.self, goldenScepter);
      if (k.a(2)) {
        const stored = Math.min(ctx.self.counter(OVERFLOW), overflowCap);
        ctx.setCounter(ctx.self, OVERFLOW, 0);
        if (stored > 0) regenerate(ctx, stored, true);
      }
      if (k.e(4)) ctx.applyStatus(ctx.self, sixteenWinters);
      if (k.e(6)) {
        ctx.addCounter(ctx.self, ULTIMATES, 1);
        // Ultimates 1, 4, 7, ...: the first, then once per 3 more.
        if ((ctx.self.counter(ULTIMATES) - 1) % k.rankParam(6, 2) === 0) {
          regenerate(ctx, k.rankParam(6, 3), true);
        }
      }
      regenerate(ctx, ULTIMATE_ENERGY, false);
    },
  });

  // "Release, the Golden Scepter": the extra AoE instance depends on the
  // enemy count, so one variant per count is chosen by the turn policy.
  const enhancedBasic = (id: string, extra: number | null) =>
    k.ability({
      id,
      kind: "basic",
      energy: 0,
      hits: [
        { shape: "aoe", each: k.param("08", 1), toughness: { each: 20 } },
        ...(extra === null ? [] : [{ shape: "aoe" as const, each: extra }]),
      ],
      before: (ctx) => {
        ctx.removeStatus(ctx.self, goldenScepter);
        gainResonance(ctx, k.param("08", 2));
      },
      after: (ctx) => {
        regenerate(ctx, ENHANCED_BASIC_ENERGY, false);
        if (k.e(1)) gainResonance(ctx, k.rankParam(1, 2));
        if (k.a(1)) ctx.applyStatus(ctx.self, manaBurst);
      },
    });
  enhancedBasic("enhancedBasic", null);
  enhancedBasic("enhancedBasic2", k.param("08", 3));
  enhancedBasic("enhancedBasic1", k.param("08", 4));

  // Skill every turn it can (it either banks Core Resonance or cashes it in
  // for a full Energy bar); Release is forced after the Ultimate.
  k.policy({
    turn: (view) => {
      if (view.self.has(goldenScepter)) {
        const count = view.enemies.length;
        return count === 1
          ? "enhancedBasic1"
          : count === 2
            ? "enhancedBasic2"
            : "enhancedBasic";
      }
      return view.skillPoints >= 1 ? "skill" : "basic";
    },
  });
});
