import { canonicalCharacterId } from "@/domain/characterIdentity";
import type { BattleApi, PolicyView, UnitView } from "../../kit/api";
import { defineCharacter } from "../../kit/character";
import type { ModifierDef } from "../../kit/model";

/** Trailblazer (Remembrance) — Remembrance, Ice. */
export default defineCharacter("8007", (k) => {
  // Both Trailblazer variants use servant 18007 and its skill IDs.
  const MEM = "18007";
  // Mem's Charge as a fraction (1 = 100%), kept on the Trailblazer.
  const CHARGE = "mem-charge";
  const SUMMONED = "mem-summoned";
  // 1 after the 100% Charge immediate action, until Mem uses its Support.
  const RUSHED = "mem-rushed";
  const energySeen = (unit: UnitView) => `energy-seen:${unit.id}`;
  const supportPaths = new Set(["Shaman", "Priest", "Knight"]);
  // Remembrance supports (Hyacine, Robin • Summeretto, Cyrene).
  const supportIds = new Set(["1409", "1415", "1512"]);

  const supportModifiers: ModifierDef[] = [
    { stat: "trueDmg", value: k.param("1800707", 1) },
  ];
  if (k.a(3)) {
    supportModifiers.push({
      stat: "trueDmg",
      scaling: {
        source: "holder",
        stat: "maxEnergy",
        threshold: k.traceParam(3, 1),
        step: k.traceParam(3, 2),
        ratio: k.traceParam(3, 3),
        cap: k.traceParam(3, 4),
      },
    });
  }
  if (k.e(1))
    supportModifiers.push({ stat: "critRate", value: k.rankParam(1, 1) });
  // E1 spreads it to the target's memosprite or memomaster; it cannot stack.
  const support = k.status({
    id: "mems-support",
    origin: "memospriteSkill",
    duration: { turns: k.param("1800707", 2) },
    unique: true,
    modifiers: supportModifiers,
  });
  const supportE4 = k.status({
    id: "mems-support-e4",
    origin: "e4",
    duration: { turns: k.param("1800707", 2) },
    unique: true,
    modifiers: [{ stat: "trueDmg", value: k.rankParam(4, 2) }],
  });
  // Mem's Talent aura, present while Mem is on the field.
  const friends = k.status({
    id: "friends-together",
    origin: "memospriteTalent",
    modifiers: [
      {
        stat: "critDmg",
        value: k.param("1800703", 2),
        scaling: {
          source: "applier",
          stat: "critDmg",
          ratio: k.param("1800703", 1),
        },
      },
    ],
  });

  // E6: "Ultimate's CRIT Rate is set at 100%" (CRIT Rate is capped at 100%).
  if (k.e(6)) {
    k.stat("e6", {
      stat: "critRate",
      value: 1,
      filter: { tags: ["ultimate"] },
    });
  }

  const findMem = (ctx: BattleApi, owner: UnitView) =>
    ctx.findSummon(owner, MEM);

  const spreadAura = (ctx: BattleApi, owner: UnitView) => {
    if (!findMem(ctx, owner)) return;
    for (const ally of ctx.allies) {
      if (ally.kind === "summon" || ally.has(friends)) continue;
      ctx.applyStatus(ally, friends);
    }
  };

  // "When the Charge reaches 100%, Mem immediately takes action." Weighted
  // triggers (enemy attacks) wait for the next whole event.
  const checkCharge = (ctx: BattleApi, owner: UnitView) => {
    if (ctx.weight < 1 - 1e-9) return;
    if (owner.counter(CHARGE) + 1e-9 < 1 || owner.counter(RUSHED) > 0) return;
    const mem = findMem(ctx, owner);
    if (!mem) return;
    ctx.advanceAction(mem, 1);
    ctx.setCounter(owner, RUSHED, 1);
  };

  const gainCharge = (ctx: BattleApi, owner: UnitView, amount: number) => {
    ctx.addCounter(owner, CHARGE, amount, 1);
    checkCharge(ctx, owner);
  };

  const summonMem = (ctx: BattleApi, owner: UnitView): UnitView => {
    const present = findMem(ctx, owner);
    if (present) return present;
    const mem = ctx.summon(owner, MEM);
    spreadAura(ctx, owner);
    let charge = k.param("1800705", 1);
    if (k.a(1) && owner.counter(SUMMONED) === 0) charge += k.traceParam(1, 2);
    ctx.setCounter(owner, SUMMONED, 1);
    gainCharge(ctx, owner, charge);
    return mem;
  };

  // Talent: "For every 10 Energy regenerated by all allies in total, Mem
  // gains 1% Charge." There is no Energy event: Energy gained by ally
  // Characters is sampled at turns, actions, and enemy hits (Energy spent
  // on an Ultimate between two samples hides gains made in between).
  const perCharge = k.param("04", 3);
  const sampleEnergy = (ctx: BattleApi) => {
    let gained = 0;
    for (const ally of ctx.allies) {
      if (ally.kind !== "character") continue;
      const key = energySeen(ally);
      const delta = ally.energy - ctx.self.counter(key);
      if (delta > 0) gained += delta;
      ctx.setCounter(ctx.self, key, ally.energy);
    }
    // "Mem gains 1% Charge" (no placeholder); only while Mem is present.
    if (gained > 0 && findMem(ctx, ctx.self)) {
      ctx.setCounter(
        ctx.self,
        CHARGE,
        Math.min(1, ctx.self.counter(CHARGE) + (gained / perCharge) * 0.01)
      );
    }
    // Also resolves a 100% Charge reached during a weighted trigger.
    checkCharge(ctx, ctx.self);
  };

  k.on("battleStart", "talent", { subject: "any" }, (ctx) => {
    for (const ally of ctx.allies) {
      if (ally.kind === "character") {
        ctx.setCounter(ctx.self, energySeen(ally), ally.energy);
      }
    }
    if (k.a(1)) ctx.advanceAction(ctx.self, k.traceParam(1, 1));
  });
  for (const event of [
    "turnStart",
    "turnEnd",
    "actionStart",
    "actionEnd",
  ] as const) {
    k.on(event, "talent", { subject: "any" }, (ctx) => sampleEnergy(ctx));
  }
  k.on("hitByEnemy", "talent", { subject: "ally" }, (ctx) => sampleEnergy(ctx));

  k.on("actionStart", "memospriteTalent", { subject: "ally" }, (ctx) =>
    spreadAura(ctx, ctx.self)
  );

  if (k.e(2)) {
    k.on(
      "turnStart",
      "e2",
      {
        subject: "ally",
        limitPerOwnTurn: k.rankParam(2, 2),
        when: (event, self) =>
          event.unit.kind === "memosprite" &&
          !(event.unit.owner === self && event.unit.definitionId === MEM),
      },
      (ctx) => ctx.gainEnergy(ctx.self, k.rankParam(2, 1))
    );
  }

  // Memosprites have no Energy bar, so E4 counts ally Characters only.
  if (k.e(4)) {
    k.on(
      "actionStart",
      "e4",
      {
        subject: "ally",
        abilityKinds: ["basic", "skill", "ultimate"],
        when: (event) =>
          event.unit.kind === "character" && event.unit.maxEnergy === 0,
      },
      (ctx) => gainCharge(ctx, ctx.self, k.rankParam(4, 1))
    );
  }

  k.ability({
    id: "basic",
    kind: "basic",
    hits: [
      { shape: "single", main: k.param("01", 1), toughness: { main: 10 } },
    ],
  });

  k.ability({
    id: "skill",
    kind: "skill",
    target: "none",
    before: (ctx) => {
      if (findMem(ctx, ctx.self)) {
        gainCharge(ctx, ctx.self, k.param("02", 2));
      } else {
        summonMem(ctx, ctx.self);
      }
    },
  });

  k.ability({
    id: "ultimate",
    kind: "ultimate",
    target: "none",
    attack: true,
    before: (ctx) => {
      const mem = summonMem(ctx, ctx.self);
      gainCharge(ctx, ctx.self, k.param("03", 2));
      // Mem deals the Ultimate's DMG: Ultimate DMG dealt by a memosprite.
      ctx.deal(
        {
          shape: "aoe",
          each: k.param("03", 1),
          toughness: { each: 20 },
        },
        { attacker: mem, tags: ["ultimate", "memosprite"] }
      );
    },
  });

  // Mem's Support goes to the first ally Character outside the support
  // Paths (Harmony, Abundance, Preservation) and the Remembrance supports
  // in team order, else to the first other ally Character, else to the
  // Trailblazer.
  const supportTarget = (view: PolicyView): UnitView => {
    const owner = view.self.owner ?? view.self;
    const characters = view.allies.filter(
      (ally) => ally.kind === "character" && ally !== owner
    );
    return (
      characters.find(
        (ally) =>
          !supportPaths.has(ally.pathId) &&
          !supportIds.has(canonicalCharacterId(ally.definitionId))
      ) ??
      characters[0] ??
      owner
    );
  };

  const applySupport = (ctx: BattleApi, unit: UnitView) => {
    ctx.applyStatus(unit, support);
    if (k.e(4) && unit.kind === "character" && unit.maxEnergy === 0) {
      ctx.applyStatus(unit, supportE4);
    }
  };

  k.memosprite({
    servantId: MEM,
    // "Mem has an initial SPD of 130."
    speed: { flat: k.param("04", 1) },
    policy: (view) =>
      (view.self.owner?.counter(CHARGE) ?? 0) + 1e-9 >= 1
        ? { ability: "support", target: supportTarget(view) }
        : "baddies",
    abilities: [
      {
        id: "baddies",
        kind: "memospriteSkill",
        energy: 10,
        hits: [
          {
            shape: "bounce",
            each: k.param("1800701", 1),
            bounces: k.param("1800701", 2),
            toughness: { each: 5 },
          },
          {
            shape: "aoe",
            each: k.param("1800701", 3),
            toughness: { each: 10 },
          },
        ],
        after: (ctx) => {
          const owner = ctx.self.owner;
          if (owner && k.a(2)) gainCharge(ctx, owner, k.traceParam(2, 1));
        },
      },
      {
        id: "support",
        kind: "memospriteSkill",
        target: "ally",
        energy: 10,
        before: (ctx) => {
          const owner = ctx.self.owner;
          const target = ctx.target ?? owner;
          if (!owner || !target) return;
          // The Charge is spent on this action.
          ctx.setCounter(owner, CHARGE, 0);
          ctx.setCounter(owner, RUSHED, 0);
          if (target !== ctx.self) {
            ctx.advanceAction(target, k.param("1800707", 3));
          }
          applySupport(ctx, target);
          if (k.e(1)) {
            for (const ally of ctx.allies) {
              if (ally.owner === target || target.owner === ally) {
                applySupport(ctx, ally);
              }
            }
          }
        },
      },
    ],
  });

  // Skill to summon Mem; Basic ATK while Mem is on the field.
  k.policy({
    turn: (view) =>
      view.allies.some(
        (ally) => ally.owner === view.self && ally.definitionId === MEM
      )
        ? "basic"
        : "skill",
  });
});
