/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 64b28d5c3dafc2cbb0b685e7ddac767f)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	APP_ID: "ggstarrail";
	ALLOWED_ORIGIN: "https://hsr.ggartifact.com,http://localhost:5173,http://127.0.0.1:41737";
	HOYOLAB_CN_PAGE_HASH: "#/hsr";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ID" | "ALLOWED_ORIGIN" | "HOYOLAB_CN_PAGE_HASH">> {}
}
