"""Refresh the small UI affiliation lookup from the pinned, independent HSR source.

Usage: python scripts/sync-character-affiliations.py <TurnBasedGameData checkout>
Localized camp labels live in the typed catalogs; unknown camp IDs fail closed.
"""

import json
import subprocess
import sys
from pathlib import Path

REVISION = "8cdb905dc2f8e6fffa9be4eb07af3e34435d6091"
source = sys.argv[1]


def read(name):
    return json.loads(subprocess.check_output([
        "git", "-C", source, "show", f"{REVISION}:ExcelOutput/{name}.json"
    ]))


affiliations = {
    str(row["AvatarID"]): str(row["CampID"])
    for row in read("AvatarAtlas") if row.get("CampID")
}
for row in read("MultiplePathAvatarConfig"):
    character, base = str(row["AvatarID"]), str(row["BaseAvatarID"])
    if character not in affiliations and base in affiliations:
        affiliations[character] = affiliations[base]

if not set(affiliations.values()).issubset({str(i) for i in range(100, 121)}):
    raise ValueError("New affiliations require typed English and Chinese labels")

target = Path(__file__).resolve().parents[1] / "src/providers/reference/characterAffiliations.ts"
output = (
    "// Generated by scripts/sync-character-affiliations.py.\n"
    f"// AvatarAtlas + MultiplePathAvatarConfig at {REVISION}.\n"
    "// Missing entries remain unknown; never infer affiliation from ID ranges.\n"
    "export const characterAffiliationIds: Readonly<Record<string, string>> = "
    + json.dumps(dict(sorted(affiliations.items())), indent=2) + ";\n"
)
target.with_suffix(".ts.new").write_text(output, encoding="utf-8")
print(f"Review {target.name}.new, then replace {target.name} ({len(affiliations)} entries).")
